version: "3.8"

services:
  nginx:
    build:
      dockerfile: dockerfiles/nginx.dockerfile
      context: .
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    environment:
      NGINX_HOST: rembish.org www.rembish.org alex.rembish.org aleksey.rembish.org
      NGINX_HTTP_PORT: "80"
      NGINX_HTTPS_PORT: "443"
      UWSGI_HOST: uwsgi
      UWSGI_PORT: 5000
      SSL_CERTIFICATE: /etc/letsencrypt/live/rembish.org/fullchain.pem
      SSL_CERTIFICATE_KEY: /etc/letsencrypt/live/rembish.org/privkey.pem
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    links:
      - uwsgi

  uwsgi:
    build:
      dockerfile: dockerfiles/uwsgi.dockerfile
      context: .
    environment:
      UWSGI_PROCESSES: "4"
      UWSGI_SOCKET: ":5000"

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
