version: "3.8"

services:
  nginx:
    build:
      dockerfile: dockerfiles/nginx.dockerfile
      context: .
    volumes:
      - ./nginx:/etc/nginx/templates:ro
      - ./rembish_org/static:/app/static:ro
      - ./ssl:/app/ssl:ro
      - ./node_modules:/node_modules:ro
      - ./ssl/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - ./ssl/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
    environment:
      NGINX_HOST: dev.rembish.org
      SSL_CERTIFICATE: /app/ssl/dev.rembish.org.crt
      SSL_CERTIFICATE_KEY: /app/ssl/dev.rembish.org.key

  uwsgi:
    build:
      dockerfile: dockerfiles/uwsgi.dockerfile
      context: .
    volumes:
      - ./rembish_org:/app/rembish_org:ro
    ports:
      - "5000:5000"
    environment:
      UWSGI_PY_AUTORELOAD: "1"
      FLASK_DEBUG: "1"
      FLASK_ENV: "development"
      DB_HOST: database
    links:
      - database

  database:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:  # All sensitive data were generated only for dev environment
      MYSQL_ROOT_PASSWORD: KlaJc6taROo6Qq3kepmA
      MYSQL_DATABASE: rembish_org
      MYSQL_USER: alex
      MYSQL_PASSWORD: 3V1fgJe8Ss0rZiiGkA0R

volumes:
  db-data:
