version: "3.8"

services:
  nginx:
    image: rembish/rembish-org-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      NGINX_HTTP_PORT: "80"
      NGINX_HTTPS_PORT: "443"
      UWSGI_HOST: uwsgi
      UWSGI_PORT: 5000
    links:
      - uwsgi

  uwsgi:
    image: rembish/rembish-org-uwsgi:latest
    environment:
      UWSGI_PROCESSES: "4"
      UWSGI_SOCKET: ":5000"
    env_file:
      - ./secrets
