version: "3.8"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/templates:ro
      - ./rembish_org/static:/app/static:ro
      - ./ssl:/app/ssl:ro
      - ./node_modules:/node_modules
    ports:
      - "443:443"
    environment:
      NGINX_HOST: dev.rembish.org
      NGINX_PORT: "443"
      SSL_CERTIFICATE: /app/ssl/dev.rembish.org.crt
      SSL_CERTIFICATE_KEY: /app/ssl/dev.rembish.org.key
      UWSGI_HOST: uwsgi
      UWSGI_PORT: 5000
    links:
      - uwsgi

  uwsgi:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./rembish_org:/app/rembish_org:ro
    environment:
      UWSGI_PROCESSES: "4"
      UWSGI_SOCKET: ":5000"
      UWSGI_PY_AUTORELOAD: "1"
      FLASK_DEBUG: "1"
      FLASK_ENV: "development"
