"""Additional flights parameters

Revision ID: 2655d07019c7
Revises: 93616835d8f5
Create Date: 2020-10-29 14:11:41.298936

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2655d07019c7'
down_revision = '93616835d8f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drone_flight_log', sa.Column('in_air', sa.Boolean(), nullable=True, default=False))
    op.add_column('drone_takeoffs', sa.Column('distance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drone_takeoffs', 'distance')
    op.drop_column('drone_flight_log', 'in_air')
    # ### end Alembic commands ###
