"""Take-off max altitude

Revision ID: 48b8855c4601
Revises: 89dd834a9d2e
Create Date: 2020-11-10 19:51:57.936580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48b8855c4601'
down_revision = '89dd834a9d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drone_takeoffs', sa.Column('altitude', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drone_takeoffs', 'altitude')
    # ### end Alembic commands ###
