"""Traveler for trip

Revision ID: 8339c7e34426
Revises: f43e8b3911e3
Create Date: 2021-02-01 14:27:01.550037

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8339c7e34426'
down_revision = 'f43e8b3911e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('traveler_id', sa.SmallInteger(), nullable=False))
    op.create_foreign_key(None, 'trips', 'users', ['traveler_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_column('trips', 'traveler_id')
    # ### end Alembic commands ###
