"""Storing Google Place ID

Revision ID: 89dd834a9d2e
Revises: 63c792a00dab
Create Date: 2020-11-10 19:16:42.155891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89dd834a9d2e'
down_revision = '63c792a00dab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drone_flight_log', sa.Column('place_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drone_flight_log', 'place_id')
    # ### end Alembic commands ###
