"""Flight log

Revision ID: 93616835d8f5
Revises: f9888fb05379
Create Date: 2020-10-27 13:02:54.604416

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '93616835d8f5'
down_revision = 'f9888fb05379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drone_flight_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drone_id', sa.SmallInteger(), nullable=False),
    sa.Column('date', sa.Date(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('activity', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['drone_id'], ['drones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drone_takeoffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Time(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('finish', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['drone_flight_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drone_takeoffs')
    op.drop_table('drone_flight_log')
    # ### end Alembic commands ###
