"""Drones

Revision ID: f9888fb05379
Revises: f4064b687c58
Create Date: 2020-10-27 12:23:56.613658

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f9888fb05379'
down_revision = 'f4064b687c58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drone_vendors',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drone_models',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('vendor_id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['drone_vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drones',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('owner_id', sa.SmallInteger(), nullable=False),
    sa.Column('model_id', sa.SmallInteger(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('serial', sa.String(length=100), nullable=False),
    sa.Column('callsign', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['drone_models.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drones')
    op.drop_table('drone_models')
    op.drop_table('drone_vendors')
    # ### end Alembic commands ###
