"""Countries

Revision ID: ffd2fa4da6f7
Revises: 3fbfe2ae6aef
Create Date: 2020-11-23 12:11:20.181350

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ffd2fa4da6f7'
down_revision = '3fbfe2ae6aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('geoname_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('south', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('west', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('north', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('east', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('geoname_id')
    )
    op.add_column('drone_flight_log', sa.Column('country_id', sa.SmallInteger(), nullable=True))
    op.create_foreign_key(None, 'drone_flight_log', 'countries', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drone_flight_log', type_='foreignkey')
    op.drop_column('drone_flight_log', 'country_id')
    op.drop_table('countries')
    # ### end Alembic commands ###
