class Configuration:
    CONTACTS_MAP_CODE = "pujeletupu"  # Generated by mapy.cz

    ME_NAME = "Alex Rembish"
    ME_EMAIL = "alex@rembish.org"


class DevelopmentConfiguration(Configuration):
    # All sensitive data here was randomly generated by random.org and used only in dev environment.
    SECRET_KEY = r"3PhbRh2bJrfgN1K8AS9Q"


class ProductionConfiguration(Configuration):
    pass
