name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push nginx image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: rembish/rembish-org-nginx
          dockerfile: dockerfiles/nginx.dockerfile
          tags: latest
      - name: Build and push uwsgi image
          uses: docker/build-push-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            repository: rembish/rembish-org-uwsgi
            dockerfile: dockerfiles/uwsgi.dockerfile
            tags: latest
