name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push nginx image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: rembish/rembish-org-nginx
          dockerfile: dockerfiles/nginx.dockerfile
          tags: latest
      - name: Build and push uwsgi image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: rembish/rembish-org-uwsgi
          dockerfile: dockerfiles/uwsgi.dockerfile
          tags: latest
      - name: Copying basic docker-compose.yaml
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMBISHORG_HOST }}
          username: ${{ secrets.REMBISHORG_USERNAME }}
          key: ${{ secrets.REMBISHORG_KEY }}
          source: "docker-compose.yaml"
          target: "rembish_org/"
      - name: Copying basic extended for production docker-compose.yaml
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMBISHORG_HOST }}
          username: ${{ secrets.REMBISHORG_USERNAME }}
          key: ${{ secrets.REMBISHORG_KEY }}
          source: "docker-compose.prod.yaml"
          target: "rembish_org/"
      - name: Applying new configuration and restarting containers
        uses: appleboy/ssh-action@master
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          host: ${{ secrets.REMBISHORG_HOST }}
          username: ${{ secrets.REMBISHORG_USERNAME }}
          key: ${{ secrets.REMBISHORG_KEY }}
          script: |
            cd rembish_org
            mv -f docker-compose.prod.yaml docker-compose.override.yaml
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
            docker pull rembish/rembish-org-nginx:latest
            docker pull rembish/rembish-org-uwsgi:latest
            docker-compose up -d --force-recreate
