name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push nginx container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfiles/nginx.dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            rembish/rembish-org-nginx:latest
      - name: Build and push uwsgi container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfiles/uwsgi.dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            rembish/rembish-org-uwsgi:latest
